"""Ausgangsstand des Schemas

Revision ID: 379f500cf7f8
Revises: 
Create Date: 2026-08-27 17:18:22.300150
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '379f500cf7f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('backup_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('include_profiles', sa.Boolean(), nullable=False),
    sa.Column('include_containers', sa.Boolean(), nullable=False),
    sa.Column('include_database', sa.Boolean(), nullable=False),
    sa.Column('keep_daily', sa.Integer(), nullable=False),
    sa.Column('keep_weekly', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('glyph', sa.String(length=8), nullable=False),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('registries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.BigInteger(), nullable=True),
    sa.Column('workspace_count', sa.Integer(), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_recovery', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('template_slug', sa.String(length=128), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_kind'), 'backups', ['kind'], unique=False)
    op.create_index(op.f('ix_backups_started_at'), 'backups', ['started_at'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_index(op.f('ix_backups_username'), 'backups', ['username'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('image_ref', sa.String(length=512), nullable=False),
    sa.Column('cores', sa.Float(), nullable=False),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=False),
    sa.Column('x_res', sa.Integer(), nullable=False),
    sa.Column('y_res', sa.Integer(), nullable=False),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_script', sa.Text(), nullable=False),
    sa.Column('persistence_scope', sa.String(length=16), nullable=False),
    sa.Column('idle_minutes', sa.Integer(), nullable=False),
    sa.Column('idle_action', sa.String(length=16), nullable=False),
    sa.Column('session_time_limit', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('source_registry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_registry_id'], ['registries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('group_templates',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'template_id')
    )
    op.create_table('image_builds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('base_image', sa.String(length=512), nullable=False),
    sa.Column('apt_packages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vscode_extensions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('setup_script', sa.Text(), nullable=False),
    sa.Column('comment', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('digest', sa.String(length=128), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('built_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version')
    )
    op.create_index(op.f('ix_image_builds_status'), 'image_builds', ['status'], unique=False)
    op.create_index(op.f('ix_image_builds_template_id'), 'image_builds', ['template_id'], unique=False)
    op.create_table('registry_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(length=64), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('architectures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('image_ref', sa.String(length=512), nullable=False),
    sa.Column('available_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncompressed_size_mb', sa.Integer(), nullable=False),
    sa.Column('imported_template_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['imported_template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registry_id'], ['registries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_id', 'sha')
    )
    op.create_index(op.f('ix_registry_entries_registry_id'), 'registry_entries', ['registry_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cores', sa.Float(), nullable=False),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=False),
    sa.Column('vnc_user', sa.String(length=64), nullable=False),
    sa.Column('vnc_secret', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_template_id'), 'sessions', ['template_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('template_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=False),
    sa.Column('exec_cmd', sa.String(length=512), nullable=False),
    sa.Column('exec_args', sa.String(length=512), nullable=False),
    sa.Column('registry_hint', sa.String(length=64), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('fixed_display', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'slug')
    )
    op.create_index(op.f('ix_template_apps_template_id'), 'template_apps', ['template_id'], unique=False)
    op.create_table('template_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('cores', sa.Float(), nullable=True),
    sa.Column('memory_bytes', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'scope', 'target_id')
    )
    op.create_index(op.f('ix_template_overrides_template_id'), 'template_overrides', ['template_id'], unique=False)
    op.create_table('app_streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('app_slug', sa.String(length=64), nullable=False),
    sa.Column('display_num', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_streams_session_id'), 'app_streams', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_streams_session_id'), table_name='app_streams')
    op.drop_table('app_streams')
    op.drop_index(op.f('ix_template_overrides_template_id'), table_name='template_overrides')
    op.drop_table('template_overrides')
    op.drop_index(op.f('ix_template_apps_template_id'), table_name='template_apps')
    op.drop_table('template_apps')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_template_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_registry_entries_registry_id'), table_name='registry_entries')
    op.drop_table('registry_entries')
    op.drop_index(op.f('ix_image_builds_template_id'), table_name='image_builds')
    op.drop_index(op.f('ix_image_builds_status'), table_name='image_builds')
    op.drop_table('image_builds')
    op.drop_table('group_templates')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_table('templates')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_backups_username'), table_name='backups')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_started_at'), table_name='backups')
    op.drop_index(op.f('ix_backups_kind'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('registries')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('backup_policies')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
